// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr2NwDgDsTo-9A_smXzTgDwWcpyMNE21Q',
    appId: '1:462105545761:web:72f0b12d8ca0a96f1b2760',
    messagingSenderId: '462105545761',
    projectId: 'adiantedoe',
    authDomain: 'adiantedoe.firebaseapp.com',
    storageBucket: 'adiantedoe.firebasestorage.app',
    measurementId: 'G-S621EZJBTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUN7U5Dj7ohn33XZ3z70E_q6ZA-wwwDD0',
    appId: '1:462105545761:android:9dcefde0f712ac2e1b2760',
    messagingSenderId: '462105545761',
    projectId: 'adiantedoe',
    storageBucket: 'adiantedoe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsqew8o-fjBVwaWK8eoyvC6XFCGkjYtvQ',
    appId: '1:462105545761:ios:7e6a654755ecfc961b2760',
    messagingSenderId: '462105545761',
    projectId: 'adiantedoe',
    storageBucket: 'adiantedoe.firebasestorage.app',
    iosBundleId: 'com.example.adiantedoe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsqew8o-fjBVwaWK8eoyvC6XFCGkjYtvQ',
    appId: '1:462105545761:ios:7e6a654755ecfc961b2760',
    messagingSenderId: '462105545761',
    projectId: 'adiantedoe',
    storageBucket: 'adiantedoe.firebasestorage.app',
    iosBundleId: 'com.example.adiantedoe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr2NwDgDsTo-9A_smXzTgDwWcpyMNE21Q',
    appId: '1:462105545761:web:51d79f6a1614afd91b2760',
    messagingSenderId: '462105545761',
    projectId: 'adiantedoe',
    authDomain: 'adiantedoe.firebaseapp.com',
    storageBucket: 'adiantedoe.firebasestorage.app',
    measurementId: 'G-SMCDEFD6TE',
  );
}
